name: workflow-pull-request
on:
  pull_request:
    branches:
      - main
jobs:
  build_and_test:
    runs-on: ubuntu-lastest
    steps:
      - name: Validame el repositorio
        use: actions/ckeckout@v2

      - name: Validar python
        uses: actions/setup.python@v2
        with:
          python-version: "3.9.6"
          architecture: "x64"

      - name: Instalar librerias
        run: pip3 install -r requeriments.txt

      - name: Correr los test
        run: python3 -m unittest -v
      
    
