name: workflow-pull-request
on:
  pull_request:
    branches:
      - main
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Validame el repositorio
        uses: actions/checkout@v2

      - name: Validar python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.6"
          architecture: "x64"

      - name: Instalar librerias
        run: pip3 install -r requirements.txt

      - name: Correr los test
        run: python3 -m unittest -v
      
    
# https://github.com/jach88/test_ci_cd_python